### ISSUE TITLE
Error instead of usage when calling examples without arguments

### ISSUE THREAD

**Issue by vanbalken** [vanbalken/arris-tg2492lg#6]
An error is shown when an example is executed without arguments. Expected that usage is shown.

```
$ python3 list_online_devices.pyTraceback (most recent call last):
  File "list_online_devices.py", line 45, in <module>
    main()
  File "list_online_devices.py", line 29, in main
    devices = connect_box.get_connected_devices()
  File "/home/arjan/Projects/arris-tg2492lg/arris_tg2492lg/connect_box.py", line 39, in get_connected_devices
    cookies = {"credential": self.token.get()}
  File "/home/arjan/Projects/arris-tg2492lg/arris_tg2492lg/single_value_cache.py", line 13, in get
    self._value = self.supplier()
  File "/home/arjan/Projects/arris-tg2492lg/arris_tg2492lg/connect_box.py", line 23, in login
    arg_string = ConnectBox.USERNAME + ":" + self.password
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by vanbalken** [comment]
Fixed in #14
